version: "3.3"
services:
  frontend:
    image: ${PROJ_NAME}-frontend:latest
    container_name: ${PROJ_NAME}-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/app:/home/node/app
      - frontend-volume/:/home/node/app/node_modules
    ports:
      - ${FRONT_DEV_PORT}:3000
      - ${FRONT_PROD_PORT}:5000
    # depends_on:
    #   - back
    tty: true
    restart: always
volumes:
  frontend-volume:
    name: ${PROJ_NAME}-volume
    driver: local
